{
 "title": "BanyanDB Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(banyandb_system_up_time,job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(banyandb_system_up_time{job=\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stats ($pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Write Rate",
   "type": "stat",
   "description": "The write rate is the number of write operations per second. It is calculated by summing the total number of written operations for measures and streams.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_measure_total_written{job=~\"$job\", pod=~\"$pod\"}[$__rate_interval])) + sum(rate(banyandb_stream_tst_total_written{job=~\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "description": "The total memory is the total physical memory available on the system, which means total amount of RAM on the system.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(banyandb_system_memory_state{job=~\"$job\", pod=~\"$pod\",kind=\"total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage ",
   "type": "stat",
   "description": "The disk usage is the percentage of disk space used. If the disk usage is over 80%, it may indicate that the disk is almost full.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(banyandb_system_disk{job=~\"$job\", pod=~\"$pod\",kind=\"used\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "stat",
   "description": "The query rate is the number of query operations per second. It is the query rate on the liaison server.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_liaison_grpc_total_started{job=~\"$job\", pod=~\"$pod\", method=\"query\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "description": "The total CPU is the total number of CPUs available on the system.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(banyandb_system_cpu_num{job=~\"$job\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write and Query Errors Rate",
   "type": "stat",
   "description": "The write and query errors rate is the number of write and query errors per minute. It is calculated by summing the total number of write and query errors from liaison and data servers.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_liaison_grpc_total_err{job=~\"$job\",pod=~\"$pod\",method=\"query\"}[$__rate_interval])*60) + sum(rate(banyandb_liaison_grpc_total_stream_msg_sent_err{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])*60) + sum(rate(banyandb_liaison_grpc_total_stream_msg_received_err{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])*60)  + sum(rate(banyandb_queue_sub_total_msg_sent_err{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registry Operation Rate",
   "type": "stat",
   "description": "The registry operation rate is the number of registry operations per second. It is calculated by summing the total number of registry operations.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_liaison_grpc_total_registry_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) + sum(rate(banyandb_liaison_grpc_total_started{job=~\"$job\",pod=~\"$pod\",method!=\"query\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Instances",
   "type": "timeseries",
   "description": "The active instances is the number of active instances in the BanyanDB cluster.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(min_over_time(up{job=~\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage ($pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "The CPU usage is the percentage of CPU used. If the CPU usage is over 80%, it may indicate that the CPU is overloaded.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=~\"$job\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RSS memory usage $pod",
   "type": "timeseries",
   "description": "The RSS memory usage is the size of resident memory used. ",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "max by (pod) (max_over_time(process_resident_memory_bytes{job=~\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage ($pod)",
   "type": "timeseries",
   "description": "The disk usage is the percentage of disk space used. If the disk usage is over 80%, it may indicate that the disk is almost full.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(sum(banyandb_system_disk{job=~\"$job\", pod=~\"$pod\", kind=\"used\"}) / sum(banyandb_system_disk{job=~\"$job\", pod=~\"$pod\", kind=\"total\"})) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network usage ($pod)",
   "type": "timeseries",
   "description": "The network usage is the number of bytes sent and received per second.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_system_net_state{job=~\"$job\",instanct=~\"$pod\",kind=\"bytes_recv\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}-recv"
    },
    {
     "expr": "sum(rate(banyandb_system_net_state{job=~\"$job\",instanct=~\"$pod\",kind=\"bytes_sent\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}-sent"
    }
   ]
  },
  { "title": "Storage ($pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Write Rate",
   "type": "timeseries",
   "description": "The write rate is the number of write operations per second. It is calculated by summing the total number of written operations for measures and streams. It's grouped by the `group` tag.\n\nYou can view the write rate of different instance to find out the hot instance.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_measure_total_written{job=~\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    },
    {
     "expr": " + sum(rate(banyandb_stream_tst_total_written{job=~\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    },
    {
     "expr": " + sum(rate(banyandb_trace_tst_total_written{job=~\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "description": "The query latency is the average query latency in seconds. It is calculated by summing the total query latency and dividing by the total number of queries.\n\nYou can view the query latency of different instance to find out the instance with high query latency. Because BanyanDB will fetch all instances to query, the query latency of the instance with high query latency will affect the overall query latency.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_liaison_grpc_total_latency{job=~\"$job\", pod=~\"$pod\",method=\"query\"}[$__rate_interval])) by( group) / sum(rate(banyandb_liaison_grpc_total_started{job=~\"$job\", pod=~\"$pod\",method=\"query\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Data",
   "type": "timeseries",
   "description": "The total data is the total number of data points stored in BanyanDB. It's grouped by the `group` tag.\n\nYou can view the total data of different instance to find out the instance with high data points. If the difference between the total data of different instances is too large, it may indicate that the data is not evenly distributed.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(banyandb_measure_total_file_elements{job=~\"$job\",pod=~\"$pod\"})by(group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(banyandb_stream_tst_total_file_elements{job=~\"$job\",pod=~\"$pod\"})by(group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(banyandb_trace_tst_total_file_elements{job=~\"$job\",pod=~\"$pod\"})by(group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merge File Rate",
   "type": "timeseries",
   "description": "The merge file rate is the number of merge file operations per minute. It is calculated by summing the total number of merge file operations. It's grouped by the `group` tag.\n\nIf the value surges, it may indicate that too many small files are being merged. It may bring following problems:\n\n- Increase the disk I/O\n- Slow down the query performance\n- Increase the CPU usage",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_measure_total_merge_loop_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval]))by(group) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(banyandb_stream_tst_total_merge_loop_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval]))by(group) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(banyandb_trace_tst_total_merge_loop_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval]))by(group) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merge File Latency",
   "type": "timeseries",
   "description": "The merge file latency is the average merge file latency in seconds. It is calculated by summing the total merge file latency and dividing by the total number of merge file operations. It's grouped by the `group` tag.\n\nIf the value surges, it may indicate that the merge file operation is slow. It may be caused by the high disk I/O and other resource usage. It may bring following problems:\n\n- Slow down the query performance\n- Increase the CPU usage\n- Increase the memory usage",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_measure_total_merge_latency{job=~\"$job\", pod=~\"$pod\",type=\"file\"}[$__rate_interval]))by(group) / sum(rate(banyandb_measure_total_merge_loop_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval]))by(group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(banyandb_stream_tst_total_merge_latency{job=~\"$job\", pod=~\"$pod\",type=\"file\"}[$__rate_interval]))by(group) / sum(rate(banyandb_stream_tst_total_merge_loop_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval]))by(group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(banyandb_trace_tst_total_merge_latency{job=~\"$job\", pod=~\"$pod\",type=\"file\"}[$__rate_interval]))by(group) / sum(rate(banyandb_trace_tst_total_merge_loop_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval]))by(group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merge File Partitions",
   "type": "timeseries",
   "description": "The merge file partitions is the average number of partitions merged per merge file operation. It is calculated by summing the total number of partitions merged and dividing by the total number of merge file operations. It's grouped by the `group` tag.\n\nIf the value surges, it may indicate that too many partitions are being merged. It may because the partition number is too large that indicates the server is under a high write load.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(banyandb_measure_total_merged_parts{job=~\"$job\", pod=~\"$pod\",type=\"file\"}[$__rate_interval]))by(group) / sum(rate(banyandb_measure_total_merge_loop_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval]))by(group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(banyandb_stream_tst_total_merged_parts{job=~\"$job\", pod=~\"$pod\",type=\"file\"}[$__rate_interval]))by(group) / sum(rate(banyandb_stream_tst_total_merge_loop_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval]))by(group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(banyandb_trace_tst_total_merged_parts{job=~\"$job\", pod=~\"$pod\",type=\"file\"}[$__rate_interval]))by(group) / sum(rate(banyandb_trace_tst_total_merge_loop_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval]))by(group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Series Write Rate",
   "type": "timeseries",
   "description": "The series write rate is the number of series write operations per second. It is calculated by summing the total number of series write operations for measures and streams. It's grouped by the `group` tag.\n\nIf the value surges, it may indicate that the old series are being updated frequently by the new series. It may be caused by the high cardinality of the series and bring following problems:\n\n- Increase the series inverted index size\n- Slow down the query performance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_measure_inverted_index_total_updates{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(banyandb_stream_storage_inverted_index_total_updates{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(banyandb_trace_storage_inverted_index_total_updates{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Series Term Search Rate",
   "type": "timeseries",
   "description": "The series term search rate is the number of series term search operations per second. It is calculated by summing the total number of series term search operations for measures and streams. It's grouped by the `group` tag.\n\nIf the value is too large, it may indicate that reading operation fetch too many series. It may be caused by the high cardinality of the series and bring following problems:\n\n- Slow down the query performance\n- Increase the CPU usage\n- Increase the memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_stream_storage_inverted_index_total_term_searchers_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(banyandb_measure_inverted_index_total_term_searchers_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "timeseries",
   "description": "The total series is the total number of series stored in BanyanDB. It's grouped by the `group` tag.\n\nIf the value is too large, it may indicate that the high cardinality of the series. It may bring following problems:\n\n- Increase the series inverted index size\n- Slow down the query performance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(banyandb_measure_inverted_index_total_doc_count{job=~\"$job\",pod=~\"$pod\"}) by (group)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(banyandb_stream_storage_inverted_index_total_doc_count{job=~\"$job\",pod=~\"$pod\"}) by (group)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stream Inverted Index ($pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Write Rate",
   "type": "timeseries",
   "description": "The write rate is the number of write operations per second. It is calculated by summing the total number of written operations for streams. It's grouped by the `group` tag.\n\nIf the value is too large, it may indicate that too many data points are being indexed and bring following problems:\n\n- Increase the inverted index size\n- Slow down the query performance\n- Increase the CPU usage\n- Increase the memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_stream_tst_inverted_index_total_updates{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Term Search Rate",
   "type": "timeseries",
   "description": "The term search rate is the number of term search operations per second. It is calculated by summing the total number of term search operations for streams. It's grouped by the `group` tag.\n\nIf the value is too large, it may indicate that reading operation fetch too many data points. It may bring following problems:\n\n- Slow down the query performance\n- Increase the CPU usage\n- Increase the memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_stream_tst_inverted_index_total_term_searchers_started{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Documents",
   "type": "timeseries",
   "description": "The total documents is the total number of documents stored in the stream inverted index. It's grouped by the `group` tag.\n\nIf the value is too large, it may indicate that too many data points are being indexed and bring following problems:\n\n- Increase the inverted index size\n- Slow down the query performance\n- Increase the CPU usage\n- Increase the memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(banyandb_stream_tst_inverted_index_total_doc_count{job=~\"$job\",pod=~\"$pod\"}) by (group)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Liaison Queue Health ($pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Liaison Queue Send Attempts",
   "type": "timeseries",
   "description": "Per-topic local send-attempt rate (frames written to the gRPC stream). End-to-end failures are in Send Errors.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_queue_pub_send_attempts_total{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Liaison Queue Send Errors (cpm)",
   "type": "timeseries",
   "description": "Send errors from liaison to data nodes, grouped by topic and reason. Reason values: non_transient, canceled, stream_canceled, retry_exhausted (local); recv_error, server_rejected (remote).",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_queue_pub_send_err_total{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])*60) by (topic,reason)",
     "legendFormat": "{{topic}} {{reason}}"
    }
   ]
  },
  {
   "title": "Liaison Queue Retries & Backoff",
   "type": "timeseries",
   "description": "Retry and backoff intensity for liaison queue sends.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(banyandb_queue_pub_send_retry_attempts_total{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}} retries"
    },
    {
     "expr": "sum(rate(banyandb_queue_pub_send_backoff_seconds_total{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}} backoff_seconds"
    }
   ]
  },
  {
   "title": "Liaison Queue Inflight",
   "type": "timeseries",
   "description": "Inflight streams and requests in liaison queue client.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(banyandb_queue_pub_inflight_streams{job=~\"$job\",pod=~\"$pod\"}) by (node)",
     "legendFormat": "{{node}} streams"
    },
    {
     "expr": "max(banyandb_queue_pub_inflight_requests{job=~\"$job\",pod=~\"$pod\"}) by (topic,node)",
     "legendFormat": "{{topic}} {{node}} inflight"
    }
   ]
  },
  {
   "title": "Chunked Sync Sessions & Failures",
   "type": "timeseries",
   "description": "Chunked sync pressure and failures observed on liaison queue_sub.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(banyandb_queue_sub_chunked_sync_active_sessions{job=~\"$job\",pod=~\"$pod\"}) by (topic)",
     "legendFormat": "{{topic}} active_sessions"
    },
    {
     "expr": "sum(rate(banyandb_queue_sub_chunked_sync_failed_parts_total{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (topic,reason)",
     "legendFormat": "{{topic}} {{reason}} failed_parts"
    },
    {
     "expr": "sum(banyandb_queue_sub_chunk_reorder_buffered_chunks{job=~\"$job\",pod=~\"$pod\"}) by (topic)",
     "legendFormat": "{{topic}} reorder_buffered"
    }
   ]
  }
 ]
}